### PR TITLE
Add `search filter`

### LINKED ISSUE #42: Missing Sub/Dub Category
I noticed that when you click on an anime it displays "All" anime whether they are sub or dub.

I suggest adding a **sub/dub** category just right under "Search Result" to allow the user to easily view them

### PR DESCRIPTION
**Pull request by chris--jones**
Add search filter (dubs or subs)
Hopefully resolves #42

Presently this relies on the title ending in "(dub)" (case insensitive) - it would be better to return this from the api as an additional property on the model as this would be more reliable and present other options (e.g. you could add colour-coded labels and make it a lot clearer which are dubs and which are subs)

Rather than hide all results if both boxes are unchecked I reverse the toggles e.g. if you uncheck dubs then unchecking subs re-checks dubs.

image

### CODE REVIEW

**Comment by chris--jones** [comment]
The colour coded labels might look something like this:
image

I've got a branch here: https://github.com/chris--jones/Sakamoto/tree/experiment/search-labels
This also makes the search logic a lot simpler, but I'm making a lot of assumptions here about this feature as well as the api being updated and the styling...

**Comment by ShivamKun** [comment]
> The colour coded labels might look something like this: image
> 
> I've got a branch here: https://github.com/chris--jones/Sakamoto/tree/experiment/search-labels This also makes the search logic a lot simpler, but I'm making a lot of assumptions here about this feature as well as the api being updated and the styling...

Exams 🥲
But I guess i'll work on that label thing. It looks really cool.
Also that reverse toggle was cool!

**Review by ShivamKun — APPROVED** [review]

**Comment by chris--jones** [comment]
@ShivamKun - I can raise a PR for the labels as per that screenshot / branch, but I do think the type of subs or dubs should be determined on the API side so it's kind of a short-term fix.

**Comment by ShivamKun** [comment]
Yea that needs to be done on the backend too...

**Pull request merged**
